/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgAddContact = (props: SVGProps<SVGSVGElement>) => (
  <svg width={56} height={56} fill="none" viewBox="0 0 56 56" {...props}>
    <path
      fill="#E5E7EA"
      fillRule="evenodd"
      d="M23.106 24.085a10.5 10.5 0 0 0 6.203-9.584C29.31 8.701 24.608 4 18.81 4S8.306 8.701 8.306 14.501c0 4.394 2.699 8.158 6.53 9.724-6.315 1.898-10.918 7.793-10.918 14.77 0 8.512 0 13.005 15.3 13.005 15.299 0 0-4.493 0-13.004 0-7.16 10.454-13.178 3.887-14.91"
      clipRule="evenodd"
    />
    <path
      fill="#F8FAFF"
      d="M41 28c6.627 0 12 5.373 12 12s-5.373 12-12 12-12-5.373-12-12 5.373-12 12-12m0 5a2 2 0 0 0-2 2v3h-3a2 2 0 1 0 0 4h3v3a2 2 0 1 0 4 0v-3h3a2 2 0 1 0 0-4h-3v-3a2 2 0 0 0-2-2"
    />
    <path
      fill="#F8FAFF"
      d="M20.889 4c5.8 0 10.5 4.701 10.5 10.501 0 4.268-2.546 7.942-6.203 9.584a15.26 15.26 0 0 1 7.107 4.197A13.33 13.33 0 0 0 25.33 40c0 4.513 2.243 8.502 5.674 10.915-2.23.719-5.346 1.085-9.705 1.085C6 52 6 47.507 6 38.995c0-6.977 4.603-12.872 10.917-14.77a10.5 10.5 0 0 1-6.53-9.724c0-5.8 4.702-10.5 10.502-10.501"
    />
  </svg>
);
export default SvgAddContact;
