/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgBackCall = (props: SVGProps<SVGSVGElement>) => (
  <svg width={44} height={44} fill="none" viewBox="0 0 44 44" {...props}>
    <path
      stroke="#EAECEF"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M15.333 22v-5A1.667 1.667 0 0 1 17 15.333h10A1.666 1.666 0 0 1 28.667 17v10A1.666 1.666 0 0 1 27 28.667h-5m-7.5-2.5a.833.833 0 0 1 .833-.834h2.5a.833.833 0 0 1 .834.834v2.5a.833.833 0 0 1-.834.833h-2.5a.833.833 0 0 1-.833-.833zM22 18.667h3.333m0 0V22m0-3.333-4.166 4.166"
    />
  </svg>
);
export default SvgBackCall;
