/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgBackToMain = (props: SVGProps<SVGSVGElement>) => (
  <svg width={21} height={20} fill="none" viewBox="0 0 21 20" {...props}>
    <g clipPath="url(#back-to-main_svg__a)">
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.667}
        d="M10.983 16.636a8.25 8.25 0 0 1-4.066-.803L3 16.667l1.083-3.25c-1.936-2.864-1.188-6.56 1.75-8.645 2.939-2.085 7.159-1.914 9.871.4 1.775 1.514 2.546 3.64 2.244 5.683m-4.115 7.478L18 14.167m0 0v3.75m0-3.75h-3.75"
      />
    </g>
    <defs>
      <clipPath id="back-to-main_svg__a">
        <path fill="currentColor" d="M.5 0h20v20H.5z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgBackToMain;
