/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgBulb = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.407}
      d="M1.667 7.714h.703M8 1.381v.704m5.63 5.63h.703M3.496 3.21l.493.492m8.515-.492-.493.492m-5.63 7.53h3.237m-3.73-.704a3.519 3.519 0 1 1 4.223 0 2.46 2.46 0 0 0-.704 2.111 1.407 1.407 0 1 1-2.815 0 2.46 2.46 0 0 0-.703-2.11"
    />
  </svg>
);
export default SvgBulb;
