/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgCall = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <g clipPath="url(#call_svg__a)">
      <path
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={1.667}
        d="M6.265 4.5h3.53l1.764 4.412-2.206 1.323a9.7 9.7 0 0 0 4.412 4.412l1.323-2.206 4.412 1.765v3.53a1.765 1.765 0 0 1-1.765 1.764A14.12 14.12 0 0 1 4.5 6.265 1.765 1.765 0 0 1 6.265 4.5"
        data-follow-stroke="currentColor"
      />
    </g>
    <defs>
      <clipPath id="call_svg__a">
        <path fill="#fff" d="M2 2h20v20H2z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgCall;
