/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgClearCircle = (props: SVGProps<SVGSVGElement>) => (
  <svg width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}>
    <path
      fill="currentColor"
      d="M6 1.5a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m0 3.615L4.498 3.613l-.885.884L5.115 6 3.613 7.502l.884.884L6 6.883l1.504 1.504.884-.885-1.503-1.503 1.503-1.502-.884-.884z"
    />
  </svg>
);
export default SvgClearCircle;
