/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgCombineAndForward = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M2.5 5c0-.46.373-.833.833-.833h3.334a.833.833 0 0 1 0 1.666H3.333A.833.833 0 0 1 2.5 5m0 5c0-.46.373-.834.833-.834h3.334a.833.833 0 0 1 0 1.667H3.333A.833.833 0 0 1 2.5 10m0 5c0-.46.373-.834.833-.834h13.334a.833.833 0 0 1 0 1.667H3.333A.833.833 0 0 1 2.5 15M10.5 5c0-.46.373-.833.833-.833h4.5c.46 0 .834.373.834.833v4.5A.833.833 0 0 1 15 9.5V7.012l-3.577 3.577a.833.833 0 0 1-1.179-1.178l3.578-3.578h-2.489A.833.833 0 0 1 10.5 5"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgCombineAndForward;
