/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeSearch = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="m19.5 19.507-5-5m-10-4.167a5.834 5.834 0 1 0 11.667 0 5.834 5.834 0 0 0-11.667 0"
    />
  </svg>
);
export default SvgComposeSearch;
