/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeEmoji = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 5.333a6.667 6.667 0 1 0 0 13.334 6.667 6.667 0 0 0 0-13.334M3.667 12a8.333 8.333 0 1 1 16.666 0 8.333 8.333 0 0 1-16.666 0"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8.667 10.333c0-.46.373-.833.833-.833h.008a.833.833 0 0 1 0 1.667H9.5a.833.833 0 0 1-.833-.834m5 0c0-.46.373-.833.833-.833h.008a.833.833 0 1 1 0 1.667H14.5a.833.833 0 0 1-.833-.834m-4.333 3.572a.833.833 0 0 1 1.178.012 2.084 2.084 0 0 0 2.976 0 .833.833 0 1 1 1.19 1.166 3.75 3.75 0 0 1-5.356 0 .833.833 0 0 1 .012-1.178"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgComposeEmoji;
