/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposePaperclip = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M11.41 4.744a4.369 4.369 0 0 1 6.18 6.179l-5.417 5.416a2.601 2.601 0 0 1-3.679-3.678l5.417-5.417a.833.833 0 1 1 1.178 1.179l-5.416 5.416a.934.934 0 1 0 1.321 1.322l5.417-5.417a2.702 2.702 0 1 0-3.822-3.821l-5.416 5.416a4.47 4.47 0 1 0 6.321 6.322l5.417-5.417a.833.833 0 1 1 1.178 1.179l-5.416 5.416a6.137 6.137 0 0 1-8.679-8.678z"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgComposePaperclip;
