/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeMicrophone = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 4.5c-.92 0-1.667.746-1.667 1.667v4.166a1.667 1.667 0 1 0 3.334 0V6.167c0-.92-.746-1.667-1.667-1.667M8.667 6.167a3.333 3.333 0 1 1 6.666 0v4.166a3.333 3.333 0 1 1-6.666 0z"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M6.167 9.5c.46 0 .833.373.833.833a5 5 0 1 0 10 0 .833.833 0 0 1 1.667 0 6.67 6.67 0 0 1-5.834 6.615v1.719h2.5a.833.833 0 0 1 0 1.666H8.667a.833.833 0 0 1 0-1.666h2.5v-1.72a6.67 6.67 0 0 1-5.834-6.614c0-.46.373-.833.834-.833"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgComposeMicrophone;
