/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeMessageMode = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M13.665 4.5v3.333a.833.833 0 0 0 .833.834h3.334"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M6.165 12V6.167A1.667 1.667 0 0 1 7.832 4.5h5.833l4.167 4.167V12M4.498 12h15m-12.5 3.333V17m3.334-1.667v5m3.333-5V17m3.333-1.667v3.334"
    />
  </svg>
);
export default SvgComposeMessageMode;
