/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeAtPerson = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M12 9.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5M7.834 12a4.167 4.167 0 1 1 8.333 0 4.167 4.167 0 0 1-8.333 0"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M9.18 4.149a8.333 8.333 0 0 1 11.153 7.852L19.5 12h.833v1.25a2.917 2.917 0 0 1-5.833 0V12a.833.833 0 0 1 1.667 0v1.25a1.25 1.25 0 1 0 2.5 0v-1.251a6.666 6.666 0 1 0-4.074 6.133.833.833 0 1 1 .648 1.536A8.332 8.332 0 1 1 9.179 4.149"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgComposeAtPerson;
