/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgComposeShareContact = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.67}
      d="M10.25 15.507h5.25m3.5-8.75v10.5a1.75 1.75 0 0 1-1.75 1.75H8.5a1.75 1.75 0 0 1-1.75-1.75v-10.5a1.75 1.75 0 0 1 1.75-1.75h8.75A1.75 1.75 0 0 1 19 6.757"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.67}
      d="M5 8.507h2.625M5 12.007h2.625M5 15.507h2.625m3.5-4.375a1.75 1.75 0 1 0 3.5 0 1.75 1.75 0 0 0-3.5 0"
    />
  </svg>
);
export default SvgComposeShareContact;
