/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgDoubleArrowLeft = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="M7.333 4.667 4 8l3.333 3.333m4-6.666L8 8l3.333 3.333"
    />
  </svg>
);
export default SvgDoubleArrowLeft;
