/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgFitWindow = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M1.667 5.238c0-.505.195-.99.542-1.347a1.83 1.83 0 0 1 1.31-.558H16.48c.491 0 .962.2 1.31.558.347.357.542.842.542 1.347v9.524c0 .505-.195.99-.542 1.347a1.83 1.83 0 0 1-1.31.558H3.518c-.49 0-.962-.201-1.31-.558a1.93 1.93 0 0 1-.542-1.347z"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M5.834 10V7.5h2.5m5.833 2.5v2.5h-2.5"
    />
  </svg>
);
export default SvgFitWindow;
