/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgForward = (props: SVGProps<SVGSVGElement>) => (
  <svg width={21} height={20} fill="none" viewBox="0 0 21 20" {...props}>
    <path
      stroke="currentColor"
      strokeWidth={1.667}
      d="m18.485 9.17-4.744-5.085a1.05 1.05 0 0 0-.55-.314 1 1 0 0 0-.617.07 1.1 1.1 0 0 0-.478.429 1.25 1.25 0 0 0-.179.646v2.558c-2.142.181-4.191 1.021-5.91 2.423-1.718 1.401-3.035 3.306-3.795 5.491a.25.25 0 0 0-.005.142.24.24 0 0 0 .073.12.2.2 0 0 0 .248.014c2.837-1.883 6.068-2.952 9.389-3.106v2.526c0 .23.062.454.18.646.116.192.283.34.478.43a1 1 0 0 0 .616.07c.208-.044.399-.153.55-.315l4.744-5.083q.152-.166.236-.382c.11-.29.11-.61 0-.9a1.2 1.2 0 0 0-.236-.38Z"
    />
  </svg>
);
export default SvgForward;
