/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgIncomingCallAccept = (props: SVGProps<SVGSVGElement>) => (
  <svg width={28} height={28} fill="none" viewBox="0 0 28 28" {...props}>
    <path
      stroke="#fff"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.844}
      d="m8.403 5.122 3.96-.1 1.855 4.9-2.512 1.546a10.12 10.12 0 0 0 4.825 4.825l1.547-2.511 4.899 1.855-.1 3.959a2.08 2.08 0 0 1-.614 1.414c-.38.38-.89.602-1.415.615-3.854-.138-7.454-1.686-10.121-4.353-2.666-2.666-4.215-6.266-4.353-10.121a2.08 2.08 0 0 1 .615-1.414c.38-.38.89-.602 1.414-.615"
    />
  </svg>
);
export default SvgIncomingCallAccept;
