/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgIncomingCallReject = (props: SVGProps<SVGSVGElement>) => (
  <svg width={28} height={28} fill="none" viewBox="0 0 28 28" {...props}>
    <path
      stroke="#fff"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.844}
      d="m24.08 15.623-2.688 2.923-4.704-2.192.672-2.923a9.66 9.66 0 0 0-6.72 0l.672 2.923-4.704 2.192-2.688-2.923a2.16 2.16 0 0 1-.556-1.461c0-.549.2-1.074.556-1.462C6.7 10.023 10.286 8.545 14 8.545s7.3 1.478 10.08 4.155c.356.388.556.914.556 1.462s-.2 1.073-.556 1.46"
    />
  </svg>
);
export default SvgIncomingCallReject;
