/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgLeaveCall = (props: SVGProps<SVGSVGElement>) => (
  <svg width={44} height={44} fill="none" viewBox="0 0 44 44" {...props}>
    <path
      fill="#fff"
      d="M22 14.5a.833.833 0 0 1 .097 1.66l-.097.007h-4.167a.833.833 0 0 0-.827.735L17 17v10a.833.833 0 0 0 .736.828l.097.005h3.75a.834.834 0 0 1 .098 1.661l-.098.006h-3.75a2.5 2.5 0 0 1-2.496-2.353L15.333 27V17a2.5 2.5 0 0 1 2.354-2.496l.146-.004zm4.756 4.553 2.356 2.358a.834.834 0 0 1 0 1.178l-2.356 2.358a.834.834 0 0 1-1.179-1.18l.935-.934H22a.833.833 0 1 1 0-1.666h4.512l-.935-.934a.833.833 0 0 1 1.179-1.18"
    />
  </svg>
);
export default SvgLeaveCall;
