/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgMediaDeviceCheck = (props: SVGProps<SVGSVGElement>) => (
  <svg width={16} height={16} fill="none" viewBox="0 0 16 16" {...props}>
    <path
      stroke="#B7BDC6"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="m3.336 8 3.333 3.333 6.667-6.666"
    />
  </svg>
);
export default SvgMediaDeviceCheck;
