/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgMicrophoneDisable = (props: SVGProps<SVGSVGElement>) => (
  <svg width={44} height={44} fill="none" viewBox="0 0 44 44" {...props}>
    <path
      stroke="#EAECEF"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M24.496 16.167a2.5 2.5 0 0 0-5 0v4.167a2.5 2.5 0 0 0 5 0zM16.164 20.334a5.833 5.833 0 0 0 5.833 5.833m0 0a5.833 5.833 0 0 0 5.834-5.833m-5.834 5.833V29.5m-3.333 0h6.667"
    />
  </svg>
);
export default SvgMicrophoneDisable;
