/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgMoreAction = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M3.75 10a1.389 1.389 0 1 1 2.778 0 1.389 1.389 0 0 1-2.778 0M8.611 10a1.389 1.389 0 1 1 2.778 0 1.389 1.389 0 0 1-2.778 0M13.473 10a1.389 1.389 0 1 1 2.777 0 1.389 1.389 0 0 1-2.777 0"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgMoreAction;
