/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgNoticeInfo = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={32}
    height={32}
    className="notice-info_svg__icon"
    viewBox="0 0 1024 1024"
    {...props}
  >
    <path
      fill="currentColor"
      d="M1023.987 518.406c0 276.477-229.245 505.594-518.393 505.594C229.117 1024 0 794.755 0 518.406 0 229.258 229.245.013 505.594.013a514.745 514.745 0 0 1 518.393 518.393M511.993 260.234a38.91 38.91 0 0 0-39.487 40.96L483.13 589.19a42.943 42.943 0 0 0 42.367 40.959h-27.135a42.43 42.43 0 0 0 42.431-41.343l10.624-287.997a39.17 39.17 0 0 0-39.424-40.511zm0 503.545a40.96 40.96 0 1 0-40.959-40.96 40.96 40.96 0 0 0 40.96 40.96m0-14.975"
    />
  </svg>
);
export default SvgNoticeInfo;
