/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgNoticeWarning = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={32}
    height={32}
    className="notice-warning_svg__icon"
    viewBox="0 0 1024 1024"
    {...props}
  >
    <path
      fill="currentColor"
      d="M1001.662 796.544c48.896 84.907 7.68 157.013-87.552 157.013H110.782c-97.835 0-139.05-69.504-90.112-157.013l401.664-666.88c48.896-87.552 128.725-87.552 177.664 0zm-522.496-500.01v341.333a32 32 0 1 0 64 0V296.533a32 32 0 1 0-64 0m0 469.333v42.666a32 32 0 1 0 64 0v-42.666a32 32 0 1 0-64 0"
    />
  </svg>
);
export default SvgNoticeWarning;
