/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgNoticeError = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={32}
    height={32}
    className="notice-error_svg__icon"
    viewBox="0 0 1024 1024"
    {...props}
  >
    <path
      fill="currentColor"
      d="M512 981.333C252.8 981.333 42.667 771.2 42.667 512S252.8 42.667 512 42.667 981.333 252.8 981.333 512 771.2 981.333 512 981.333M556.245 512 716.16 352.085a31.275 31.275 0 1 0-44.245-44.245L512 467.755 352.085 307.84a31.275 31.275 0 1 0-44.245 44.245L467.755 512 307.84 671.915a31.275 31.275 0 1 0 44.245 44.245L512 556.245 671.915 716.16a31.275 31.275 0 1 0 44.245-44.245z"
      className="notice-error_svg__selected"
      data-spm-anchor-id="a313x.7781069.0.i47"
    />
  </svg>
);
export default SvgNoticeError;
