/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgNoticeSuccess = (props: SVGProps<SVGSVGElement>) => (
  <svg
    width={32}
    height={32}
    className="notice-success_svg__icon"
    viewBox="0 0 1024 1024"
    {...props}
  >
    <path
      fill="currentColor"
      d="M512 64C264.576 64 64 264.576 64 512c0 247.36 200.576 448 448 448s448-200.64 448-448c0-247.424-200.576-448-448-448m206.72 292.16L495.36 714.944c-7.744 12.416-21.248 20.224-35.904 20.928-.576.128-1.28.128-1.92.128-14.016 0-27.136-6.592-35.648-17.664L277.696 537.472c-14.848-19.648-11.008-47.616 8.64-62.528 19.776-14.848 47.616-10.944 62.528 8.64l105.088 129.152L643.2 308.992c12.992-20.928 40.512-27.264 61.376-14.272 20.928 12.992 27.2 40.512 14.144 61.44"
    />
  </svg>
);
export default SvgNoticeSuccess;
