/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgOriginalSize = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M1.667 5.238c0-.505.195-.99.542-1.347a1.83 1.83 0 0 1 1.31-.558H16.48c.491 0 .962.2 1.31.558.347.357.542.842.542 1.347v9.524c0 .505-.195.99-.542 1.347a1.83 1.83 0 0 1-1.31.558H3.518c-.49 0-.962-.201-1.31-.558a1.93 1.93 0 0 1-.542-1.347z"
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.458}
      d="M5.834 7.5h.833v5M13.334 7.5h.833v5"
    />
    <path
      fill="currentColor"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.458}
      d="M10.365 9.201a.365.365 0 1 0 0-.729.365.365 0 0 0 0 .73M10.365 12.361a.365.365 0 1 0 0-.73.365.365 0 0 0 0 .73"
    />
  </svg>
);
export default SvgOriginalSize;
