/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgPause = (props: SVGProps<SVGSVGElement>) => (
  <svg width={14} height={16} fill="none" viewBox="0 0 14 16" {...props}>
    <path
      fill="currentColor"
      d="M2 .5A1.5 1.5 0 0 0 .5 2v12A1.5 1.5 0 0 0 2 15.5h2A1.5 1.5 0 0 0 5.5 14V2A1.5 1.5 0 0 0 4 .5zM10 .5A1.5 1.5 0 0 0 8.5 2v12a1.5 1.5 0 0 0 1.5 1.5h2a1.5 1.5 0 0 0 1.5-1.5V2A1.5 1.5 0 0 0 12 .5z"
    />
  </svg>
);
export default SvgPause;
