/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgPlay = (props: SVGProps<SVGSVGElement>) => (
  <svg width={14} height={18} fill="none" viewBox="0 0 14 18" {...props}>
    <path
      fill="currentColor"
      d="M1.751 1.043a1 1 0 0 0-1.524.852v14.21a1 1 0 0 0 1.524.852l11.546-7.105a1 1 0 0 0 0-1.704z"
    />
  </svg>
);
export default SvgPlay;
