/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgRaiseHand = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <g
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      clipPath="url(#raise-hand_svg__a)"
    >
      <path d="M6.667 10.833v-6.25a1.25 1.25 0 0 1 2.5 0m0 0V10m0-5.417V2.917a1.25 1.25 0 1 1 2.5 0V10m0-5.417a1.25 1.25 0 0 1 2.5 0V10" />
      <path d="M14.167 6.25a1.25 1.25 0 0 1 2.5 0v7.083a5 5 0 0 1-5 5H10h.174a5 5 0 0 1-4.177-2.25l-.164-.25q-.39-.598-2.738-4.773a1.25 1.25 0 0 1 .447-1.685 1.56 1.56 0 0 1 1.9.233l1.225 1.225" />
    </g>
    <defs>
      <clipPath id="raise-hand_svg__a">
        <path fill="#fff" d="M0 0h20v20H0z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgRaiseHand;
