/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSaveToNote = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M7.5 4.167A.833.833 0 0 0 6.667 5v10.195l2.904-1.743a.83.83 0 0 1 .858 0l2.904 1.743V5a.834.834 0 0 0-.833-.833zm-1.768-.935A2.5 2.5 0 0 1 7.5 2.5h5A2.5 2.5 0 0 1 15 5v11.667a.833.833 0 0 1-1.262.714L10 15.14 6.262 17.38A.833.833 0 0 1 5 16.667V5a2.5 2.5 0 0 1 .732-1.768"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgSaveToNote;
