/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSearchResult = (props: SVGProps<SVGSVGElement>) => (
  <svg width={97} height={96} fill="none" viewBox="0 0 97 96" {...props}>
    <path
      fill="var(--dst-color-divider, #2B3139)"
      fillRule="evenodd"
      d="M64.5 8h-38v80h58V28zm-28 29h38v4h-38zm0 9h38v4h-38zm38 9h-38v4h38z"
      clipRule="evenodd"
    />
    <path fill="var(--dst-color-text-third, #5E6673)" d="M84.5 28h-20V8z" />
    <path
      fill="var(--dst-color-text-third, #848E9C)"
      fillRule="evenodd"
      d="m4.671 73.172 14.5-14.5 5.657 5.657-14.5 14.5z"
      clipRule="evenodd"
    />
    <path
      fill="var(--dst-color-text-third, #848E9C)"
      fillRule="evenodd"
      d="M51.5 48c0-8.837-7.163-16-16-16s-16 7.163-16 16 7.163 16 16 16 16-7.163 16-16m4 0c0-11.046-8.954-20-20-20s-20 8.954-20 20 8.954 20 20 20 20-8.954 20-20"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgSearchResult;
