/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSearch = (props: SVGProps<SVGSVGElement>) => (
  <svg width={24} height={24} fill="none" viewBox="0 0 24 24" {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.537 6.33a4.207 4.207 0 1 0 0 8.414 4.207 4.207 0 0 0 0-8.415M4.5 10.536a6.037 6.037 0 1 1 12.073 0 6.037 6.037 0 0 1-12.073 0"
      clipRule="evenodd"
    />
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M13.548 13.548a.915.915 0 0 1 1.294 0l4.39 4.39a.915.915 0 1 1-1.293 1.294l-4.39-4.39a.915.915 0 0 1 0-1.294"
      clipRule="evenodd"
    />
  </svg>
);
export default SvgSearch;
