/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarCall = (props: SVGProps<SVGSVGElement>) => (
  <svg width={240} height={240} fill="none" viewBox="0 0 240 240" {...props}>
    <g clipPath="url(#sidebar-call_svg__a)">
      <g clipPath="url(#sidebar-call_svg__b)">
        <path fill="url(#sidebar-call_svg__c)" d="M0 0h240v240H0z" />
        <path fill="url(#sidebar-call_svg__d)" d="M0 0h240v240H0z" />
        <path fill="url(#sidebar-call_svg__e)" d="M0 0h240v240H0z" />
      </g>
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M81.5 76h22l11 27.5-13.75 8.25a60.5 60.5 0 0 0 27.5 27.5l8.25-13.75 27.5 11v22a11 11 0 0 1-11 11A88 88 0 0 1 70.5 87a11 11 0 0 1 11-11"
      />
    </g>
    <defs>
      <linearGradient
        id="sidebar-call_svg__c"
        x1={126}
        x2={-77.87}
        y1={268.8}
        y2={181.175}
        gradientUnits="userSpaceOnUse"
      >
        <stop offset={0.145} stopColor="#1773EB" />
        <stop offset={1} stopColor="#4DA0FF" />
      </linearGradient>
      <linearGradient
        id="sidebar-call_svg__d"
        x1={240.421}
        x2={-5.309}
        y1={224.348}
        y2={218.374}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#00BDB6" />
        <stop offset={1} stopColor="#4DE7DC" />
      </linearGradient>
      <linearGradient
        id="sidebar-call_svg__e"
        x1={164.5}
        x2={-38.796}
        y1={173.5}
        y2={164.165}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#01BC6A" stopOpacity={0.99} />
        <stop offset={1} stopColor="#45E386" />
      </linearGradient>
      <clipPath id="sidebar-call_svg__a">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <clipPath id="sidebar-call_svg__b">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgSidebarCall;
