/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarLayout = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M7.5 3.333v13.334M3.334 5A1.667 1.667 0 0 1 5 3.333h10A1.667 1.667 0 0 1 16.667 5v10A1.667 1.667 0 0 1 15 16.667H5A1.667 1.667 0 0 1 3.334 15z"
    />
  </svg>
);
export default SvgSidebarLayout;
