/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarImageGallery = (props: SVGProps<SVGSVGElement>) => (
  <svg width={240} height={240} fill="none" viewBox="0 0 240 240" {...props}>
    <g clipPath="url(#sidebar-image-gallery_svg__a)">
      <g clipPath="url(#sidebar-image-gallery_svg__b)">
        <path fill="url(#sidebar-image-gallery_svg__c)" d="M0 0h240v240H0z" />
        <path fill="url(#sidebar-image-gallery_svg__d)" d="M0 0h240v240H0z" />
      </g>
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M136.5 98h.055M70.5 87A16.5 16.5 0 0 1 87 70.5h66A16.5 16.5 0 0 1 169.5 87v66c0 4.376-1.738 8.573-4.833 11.667A16.5 16.5 0 0 1 153 169.5H87A16.5 16.5 0 0 1 70.5 153z"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M70.5 142 98 114.5c5.104-4.911 11.396-4.911 16.5 0L142 142"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="m131 131 5.5-5.5c5.104-4.911 11.396-4.911 16.5 0l16.5 16.5"
      />
    </g>
    <defs>
      <linearGradient
        id="sidebar-image-gallery_svg__c"
        x1={33.75}
        x2={225}
        y1={30}
        y2={251.25}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
      <linearGradient
        id="sidebar-image-gallery_svg__d"
        x1={101.5}
        x2={240}
        y1={102.5}
        y2={240}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
      <clipPath id="sidebar-image-gallery_svg__a">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <clipPath id="sidebar-image-gallery_svg__b">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgSidebarImageGallery;
