/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarCombineForward = (props: SVGProps<SVGSVGElement>) => (
  <svg width={240} height={240} fill="none" viewBox="0 0 240 240" {...props}>
    <g clipPath="url(#sidebar-combine-forward_svg__a)">
      <g clipPath="url(#sidebar-combine-forward_svg__b)">
        <path fill="url(#sidebar-combine-forward_svg__c)" d="M0 0h240v240H0z" />
      </g>
      <path
        stroke="#fff"
        strokeWidth={11}
        d="m172.701 114.516-31.31-33.555a6.9 6.9 0 0 0-3.628-2.074 6.55 6.55 0 0 0-4.071.462 7.24 7.24 0 0 0-3.156 2.833 8.24 8.24 0 0 0-1.184 4.262v16.885c-14.137 1.194-27.661 6.738-39.003 15.989-11.343 9.251-20.034 21.824-25.053 36.245a1.67 1.67 0 0 0-.027.935c.076.304.242.579.477.786a1.32 1.32 0 0 0 1.638.099c18.724-12.43 40.05-19.486 61.968-20.498v16.67c0 1.518.411 2.998 1.184 4.263s1.874 2.249 3.156 2.832a6.54 6.54 0 0 0 4.071.462c1.37-.286 2.63-1.006 3.628-2.073l31.31-33.55a7.8 7.8 0 0 0 1.556-2.519 8.3 8.3 0 0 0 0-5.94 7.8 7.8 0 0 0-1.556-2.514Z"
      />
    </g>
    <defs>
      <clipPath id="sidebar-combine-forward_svg__a">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <clipPath id="sidebar-combine-forward_svg__b">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <linearGradient
        id="sidebar-combine-forward_svg__c"
        x1={101.5}
        x2={240}
        y1={102.5}
        y2={240}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
    </defs>
  </svg>
);
export default SvgSidebarCombineForward;
