/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarEnlarge = (props: SVGProps<SVGSVGElement>) => (
  <svg width={240} height={240} fill="none" viewBox="0 0 240 240" {...props}>
    <g clipPath="url(#sidebar-enlarge_svg__a)">
      <path fill="url(#sidebar-enlarge_svg__b)" d="M0 0h240v240H0z" />
      <path fill="url(#sidebar-enlarge_svg__c)" d="M0 0h240v240H0z" />
      <g clipPath="url(#sidebar-enlarge_svg__d)">
        <path fill="url(#sidebar-enlarge_svg__e)" d="M0 0h240v240H0z" />
      </g>
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="m175 175-36.667-36.667M65 107.778a42.778 42.778 0 1 0 85.556-.001 42.778 42.778 0 0 0-85.556.001"
      />
      <path
        fill="#fff"
        fillRule="evenodd"
        d="M100.864 93.56a7.03 7.03 0 0 1 2.598-3.309c1.185-.814 4.035-1.251 4.035-1.251s2.85.437 4.036 1.251a7.03 7.03 0 0 1 2.597 3.309l9.562 25.288a4.05 4.05 0 0 1-.976 4.508 4.11 4.11 0 0 1-3.003 1.115 4.116 4.116 0 0 1-2.899-1.361 4.1 4.1 0 0 1-.824-1.401l-2.079-5.51h-12.816l-2.085 5.51a4.1 4.1 0 0 1-.824 1.401 4.11 4.11 0 0 1-2.899 1.361 4.124 4.124 0 0 1-3.004-1.115 4.052 4.052 0 0 1-.976-4.508zm3.32 14.48h6.638l-3.319-8.78z"
        clipRule="evenodd"
      />
    </g>
    <defs>
      <linearGradient
        id="sidebar-enlarge_svg__b"
        x1={101.5}
        x2={240}
        y1={102.5}
        y2={240}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
      <linearGradient
        id="sidebar-enlarge_svg__c"
        x1={101.5}
        x2={240}
        y1={102.5}
        y2={240}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
      <linearGradient
        id="sidebar-enlarge_svg__e"
        x1={33.75}
        x2={225}
        y1={30}
        y2={251.25}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
      <clipPath id="sidebar-enlarge_svg__a">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <clipPath id="sidebar-enlarge_svg__d">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
    </defs>
  </svg>
);
export default SvgSidebarEnlarge;
