/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSidebarLocalSearch = (props: SVGProps<SVGSVGElement>) => (
  <svg width={240} height={240} fill="none" viewBox="0 0 240 240" {...props}>
    <g clipPath="url(#sidebar-local-search_svg__a)">
      <g clipPath="url(#sidebar-local-search_svg__b)">
        <path fill="url(#sidebar-local-search_svg__c)" d="M0 0h240v240H0z" />
      </g>
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M123.19 163.797a54.45 54.45 0 0 1-26.84-5.297L70.5 164l7.15-21.45c-12.782-18.903-7.843-43.296 11.55-57.057 19.393-13.755 47.245-12.628 65.148 2.64 11.715 9.994 16.802 24.024 14.806 37.51"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M148.183 120.009a27.5 27.5 0 1 1-.683-.009z"
      />
      <path
        stroke="#fff"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth={11}
        d="M147.5 136.5v10.75l8.25 3"
      />
    </g>
    <defs>
      <clipPath id="sidebar-local-search_svg__a">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <clipPath id="sidebar-local-search_svg__b">
        <path fill="#fff" d="M0 0h240v240H0z" />
      </clipPath>
      <linearGradient
        id="sidebar-local-search_svg__c"
        x1={101.5}
        x2={240}
        y1={102.5}
        y2={240}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#5E6673" />
        <stop offset={1} stopColor="#474D57" />
      </linearGradient>
    </defs>
  </svg>
);
export default SvgSidebarLocalSearch;
