/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgSlowDown = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M4.697 16.137a7.5 7.5 0 1 1 12.232-8.174M13.333 7.5 10 10.833M13.333 14.167h5"
    />
  </svg>
);
export default SvgSlowDown;
