/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgStarFilled = (props: SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} fill="none" viewBox="0 0 32 32" {...props}>
    <path
      fill="currentColor"
      d="M10.99 9.787 2.484 11.02l-.151.03a1.333 1.333 0 0 0-.587 2.246l6.163 5.999-1.453 8.473-.018.147a1.333 1.333 0 0 0 1.952 1.258l7.608-4 7.591 4 .133.062a1.334 1.334 0 0 0 1.803-1.467l-1.455-8.473 6.166-6 .104-.114a1.333 1.333 0 0 0-.844-2.16l-8.507-1.234-3.803-7.707a1.334 1.334 0 0 0-2.392 0z"
    />
  </svg>
);
export default SvgStarFilled;
