/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgStar = (props: SVGProps<SVGSVGElement>) => (
  <svg width={32} height={32} fill="none" viewBox="0 0 32 32" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={2}
      d="m16 23.667-8.23 4.326 1.572-9.164-6.666-6.489 9.2-1.333 4.114-8.338 4.115 8.338 9.2 1.333-6.667 6.49 1.572 9.163z"
    />
  </svg>
);
export default SvgStar;
