/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgTabConversationActive = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      fill="url(#tab-conversation-active_svg__a)"
      d="M2.707 16.97a.417.417 0 0 1-.47-.495l.62-3.016a8.333 8.333 0 1 1 3.148 3.021zM13.69 9.19v.01z"
    />
    <circle cx={6.667} cy={9.167} r={0.833} fill="#fff" />
    <circle cx={10} cy={9.167} r={0.833} fill="#fff" />
    <circle cx={13.333} cy={9.167} r={0.833} fill="#fff" />
    <circle
      cx={15.833}
      cy={14.167}
      r={3.333}
      fill="url(#tab-conversation-active_svg__b)"
    />
    <defs>
      <linearGradient
        id="tab-conversation-active_svg__a"
        x1={18.362}
        x2={1.298}
        y1={16.413}
        y2={15.998}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#1773EB" />
        <stop offset={1} stopColor="#4DA0FF" />
      </linearGradient>
      <linearGradient
        id="tab-conversation-active_svg__b"
        x1={19.178}
        x2={12.352}
        y1={17.065}
        y2={16.899}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#009BFF" stopOpacity={0.25} />
        <stop offset={1} stopColor="#AAE0FF" />
      </linearGradient>
    </defs>
  </svg>
);
export default SvgTabConversationActive;
