/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgTabContactActive = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <rect
      width={14.167}
      height={16.667}
      x={2.5}
      y={1.667}
      fill="url(#tab-contact-active_svg__a)"
      rx={1.667}
    />
    <circle cx={9.583} cy={8.75} r={2.083} stroke="#fff" strokeWidth={1.667} />
    <path
      stroke="#fff"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M6.667 13.333c.13-.37.972-1.666 2.916-1.666 1.945 0 2.917 1.666 2.917 1.666"
    />
    <rect
      width={3.333}
      height={1.667}
      x={15}
      y={5.833}
      fill="url(#tab-contact-active_svg__b)"
      rx={0.833}
    />
    <rect
      width={3.333}
      height={1.667}
      x={15}
      y={9.167}
      fill="url(#tab-contact-active_svg__c)"
      rx={0.833}
    />
    <rect
      width={3.333}
      height={1.667}
      x={15}
      y={12.5}
      fill="url(#tab-contact-active_svg__d)"
      rx={0.833}
    />
    <defs>
      <linearGradient
        id="tab-contact-active_svg__a"
        x1={16.692}
        x2={2.184}
        y1={17.247}
        y2={16.947}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#1773EB" />
        <stop offset={1} stopColor="#4DA0FF" />
      </linearGradient>
      <linearGradient
        id="tab-contact-active_svg__b"
        x1={18.339}
        x2={14.932}
        y1={7.391}
        y2={7.226}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#45B6FF" stopOpacity={0.29} />
        <stop offset={1} stopColor="#2EB3FF" />
      </linearGradient>
      <linearGradient
        id="tab-contact-active_svg__c"
        x1={18.339}
        x2={14.932}
        y1={10.725}
        y2={10.559}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#45B6FF" stopOpacity={0.29} />
        <stop offset={1} stopColor="#2EB3FF" />
      </linearGradient>
      <linearGradient
        id="tab-contact-active_svg__d"
        x1={18.339}
        x2={14.932}
        y1={14.058}
        y2={13.892}
        gradientUnits="userSpaceOnUse"
      >
        <stop stopColor="#45B6FF" stopOpacity={0.29} />
        <stop offset={1} stopColor="#2EB3FF" />
      </linearGradient>
    </defs>
  </svg>
);
export default SvgTabContactActive;
