/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgTabConversation = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="m2.917 16.25.665-3.235a7.49 7.49 0 0 1 1.749-9.712 7.497 7.497 0 0 1 12.14 5.204 7.49 7.49 0 0 1-5.835 7.96 7.5 7.5 0 0 1-5.223-.736z"
    />
    <circle
      cx={6.667}
      cy={9.167}
      r={0.417}
      fill="currentColor"
      stroke="currentColor"
      strokeWidth={0.833}
    />
    <circle
      cx={10}
      cy={9.167}
      r={0.417}
      fill="currentColor"
      stroke="currentColor"
      strokeWidth={0.833}
    />
    <circle
      cx={13.333}
      cy={9.167}
      r={0.417}
      fill="currentColor"
      stroke="currentColor"
      strokeWidth={0.833}
    />
  </svg>
);
export default SvgTabConversation;
