/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgTabContact = (props: SVGProps<SVGSVGElement>) => (
  <svg width={20} height={20} fill="none" viewBox="0 0 20 20" {...props}>
    <path
      fill="currentColor"
      d="M14.584 6.917c0-.369.298-.667.666-.667h1.584a.667.667 0 1 1 0 1.333H15.25a.667.667 0 0 1-.666-.666m0 2.666c0-.368.298-.666.666-.666h1.584a.667.667 0 1 1 0 1.333H15.25a.667.667 0 0 1-.666-.667m0 2.667c0-.368.298-.667.666-.667h1.584a.667.667 0 0 1 0 1.334H15.25a.667.667 0 0 1-.666-.667"
    />
    <circle
      cx={9.583}
      cy={8.75}
      r={2.083}
      stroke="currentColor"
      strokeWidth={1.667}
    />
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.667}
      d="M6.667 13.333c.13-.37.972-1.666 2.916-1.666 1.945 0 2.917 1.666 2.917 1.666"
    />
    <path
      stroke="currentColor"
      strokeWidth={1.667}
      d="M15.834 14.121v1.712c0 .92-.747 1.667-1.667 1.667H5c-.92 0-1.666-.746-1.666-1.667V4.167C3.334 3.247 4.08 2.5 5 2.5h9.167c.92 0 1.667.746 1.667 1.667v.98"
    />
  </svg>
);
export default SvgTabContact;
