/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgZoomOut = (props: SVGProps<SVGSVGElement>) => (
  <svg width={14} height={14} fill="none" viewBox="0 0 14 14" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="M3.333 5.333h4m5.334 7.333-4-4m-8-3.333a4.667 4.667 0 1 0 9.333 0 4.667 4.667 0 0 0-9.333 0"
    />
  </svg>
);
export default SvgZoomOut;
