/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgZoomReset = (props: SVGProps<SVGSVGElement>) => (
  <svg width={12} height={12} fill="none" viewBox="0 0 12 12" {...props}>
    <path
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      strokeWidth={1.333}
      d="M.667 3.333V2A1.333 1.333 0 0 1 2 .667h1.333m-2.666 8V10A1.333 1.333 0 0 0 2 11.333h1.333M8.667.667H10A1.333 1.333 0 0 1 11.333 2v1.333m-2.666 8H10A1.333 1.333 0 0 0 11.333 10V8.666m-2.666 0L7 7M3.333 5.333a2 2 0 1 0 4 0 2 2 0 0 0-4 0"
    />
  </svg>
);
export default SvgZoomReset;
